### ISSUE TITLE
404 on npm run serve 

### ISSUE THREAD

**Issue by ijt** [PolymerLabs/lit-element-starter-js#2]
I ran 
```
npm i
npm run serve
```
and got the following result:
<img width="795" alt="Screen Shot 2020-05-22 at 3 25 58 PM" src="https://user-images.githubusercontent.com/15530/82714051-f1195d00-9c41-11ea-9dca-821e0bde12d0.png">

**Comment by luchoster** [comment]
I just ran into the same problem. But when you start the server, the correct path is: `http://localhost:8000/dev`
You should now see the component with the count button.

**Comment by ijt** [comment]
I see. Thank you.
